stages:
  - test_and_upload
  - name: publish
    if: branch = master
jobs:
  include:
#    - os: windows
#      stage: test_and_upload
#      env: KBUILD=windows
#      language: shell # java is not supported but jdk is installed
#      script:
#        - powershell -Command "cmd /c travis_win.bat"
#        - |
#          if [ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]; then
#            powershell -Command "cmd /c travis_win_bintray.bat"
#          fi
    - os: osx
      stage: test_and_upload
      env:
        KBUILD=macos
        JAVA_OPTS=-Xmx2g
      language: java
      jdk: openjdk10
      before_install:
        - cp $(/usr/libexec/java_home)/lib/security/cacerts "${JAVA_HOME}/lib/security/cacerts"
      install:
        - echo install
      before_script:
        - echo before_script
      script:
#        - ./gradlew -s -i check
        - |
          if [ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]; then
              chmod +x ./gradlew
            ./gradlew -s -i artifactoryPublish -DbintrayUser=$bintrayUser -DbintrayApiKey=$bintrayApiKey
          fi