stages:
  - test_and_upload
  - name: publish
    if: branch = master
jobs:
  include:
#    - os: windows
#      stage: test_and_upload
#      env: KBUILD=windows
#      language: shell # java is not supported but jdk is installed
#      script:
#        - powershell -Command "cmd /c travis_win.bat"
#        - |
#          if [ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]; then
#            powershell -Command "cmd /c travis_win_bintray.bat"
#          fi
    - os: osx
      stage: test_and_upload
      env:
        KBUILD=macos
        JAVA_OPTS=-Xmx2g
#        BINTRAY_USER=$BINTRAY_USER
#        BINTRAY_API_KEY=$BINTRAY_API_KEY
      language: java
      jdk: openjdk10
      before_install:
        - cp $(/usr/libexec/java_home)/lib/security/cacerts "${JAVA_HOME}/lib/security/cacerts"
      install:
        - echo install
      before_script:
        - echo before_script
        - chmod +x ./gradlew
      script:
        - ./gradlew -s -i check
        - ./gradlew -s -i artifactoryPublish
        - ./gradlew artifactoryPublish
        - ./gradlew artifactoryPublish
        - ./gradlew artifactoryPublish