name: Build & publish JVM API
on:
  push:
    branches:
      - develop
      - master
jobs:
  build_and_publish_for_win:
    name: Publish (windows platform)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish
        run: gradle publishWindowsX64PublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  build_and_publish_for_mac:
    name: Publish (macOS platform)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1.0.3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konans-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konans-
      - name: Publish
        run: gradle --no-daemon publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx4096m